version: "3.3"
services:
  bitcoind-regtest:
      container_name: bitcoind
      build:
        context: ../bitcoind-regtest/.
        dockerfile: ./Dockerfile
      image: lnbook/bitcoind-regtest:latest
      ports:
      - "18443:18443"
      - "12005:12005"
      - "12006:12006"
  lnd-run:
      container_name: lnd
      build:
        context: ../lnd-run
        dockerfile: ./Dockerfile
      image: lnbook/lnd-run:latest
